import mongoose from "mongoose";

const IlanSchema = new mongoose.Schema({
  link: String,
  fiyat: String,
  adres: String,
  ilan_tarihi: String,
  emlak_tipi: String,
  brut_m2: String,
  net_m2: String,
  oda_sayisi: String,
  bina_yasi: String,
  bulundugu_kat: String,
  kat_sayisi: String,
  isitma: String,
  banyo_sayisi: String,
  mutfak: String,
  balkon: String,
  asansor: String,
  otopark: String,
  esyali: String,
  kullanim_durumu: String,
  site_icerisinde: String,
  site_adi: String,
  aidat: String,
  depozito: String,
  tapu_durumu: String,
  kimden: String,
  bfoto1: String,
  bfoto2: String,
  bfoto3: String,
  bfoto4: String,
  bfoto5: String,
  bfoto6: String,
  bfoto7: String,
  bfoto8: String,
  bfoto9: String,
  bfoto10: String,
  foto1: String,
  foto2: String,
  foto3: String,
  foto4: String,
  foto5: String,
  foto6: String,
  foto7: String,
  foto8: String,
  foto9: String,
  foto10: String,
  title: String,
  emlakciadi: String,
  emlakcifoto: String,
  emlakcicep: String
}, { collection: 'ilanlar' });

const Ilan = mongoose.model('Ilan', IlanSchema);
export default Ilan;
